1:
  dynamic_human: 7
  dynamic_robot: 1
  static: 0
2:
  dynamic_human: 8
  dynamic_robot: 2
  static: 1
3:
  dynamic_human: 8
  dynamic_robot: 2
  static: 2
4:
  dynamic_human: 8
  dynamic_robot: 3
  static: 4
5:
  dynamic_human: 9
  dynamic_robot: 3
  static: 0
6:
  dynamic_human: 9
  dynamic_robot: 4
  static: 3
7:
  dynamic_human: 13
  dynamic_robot: 6
  static: 8
8:
  dynamic_human: 14
  dynamic_robot: 6
  static: 8
9:
  dynamic_human: 15
  dynamic_robot: 7
  static: 9
10:
  dynamic_human: 16
  dynamic_robot: 7
  static: 0
